### ISSUE TITLE
Provided example hello.py does not work

### ISSUE THREAD

**Issue by blokhin** [sklam/py2nb#3]
```
$ python -m py2nb hello.py hello.ipynb
/home/Evgeny/somepath/lib/python2.7/site-packages/IPython/nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated since IPython 4.0. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)
1,0-8,3:        STRING  '"""\n# Hello\n\nDemonstrate:\n* conversion of regular python script into _Jupyter notebook_\n* support **Markdown**\n* this is a list\n"""'
8,3-8,4:        NEWLINE '\n'
9,0-9,1:        NL      '\n'
10,0-10,4:      NAME    'from'
10,5-10,15:     NAME    '__future__'
10,16-10,22:    NAME    'import'
10,23-10,38:    NAME    'absolute_import'
10,38-10,39:    OP      ','
10,40-10,54:    NAME    'print_function'
10,54-10,55:    OP      ','
10,56-10,64:    NAME    'division'
10,64-10,65:    NEWLINE '\n'
11,0-11,1:      NL      '\n'
12,0-17,3:      STRING  '"""\n## Hello\n\nThis is a *hello world* function.\n\n"""'
17,3-17,4:      NEWLINE '\n'
18,0-18,1:      NL      '\n'
19,0-19,1:      NL      '\n'
20,0-20,3:      NAME    'def'
20,4-20,9:      NAME    'hello'
20,9-20,10:     OP      '('
20,10-20,11:    OP      ')'
20,11-20,12:    OP      ':'
20,12-20,13:    NEWLINE '\n'
21,0-21,4:      INDENT  '    '
21,4-23,7:      STRING  '"""\n    This is a docstring\n    """'
23,7-23,8:      NEWLINE '\n'
24,4-24,9:      NAME    'print'
24,9-24,10:     OP      '('
24,10-24,17:    STRING  '"hello"'
24,17-24,18:    OP      ')'
24,18-24,19:    NEWLINE '\n'
25,0-25,1:      NL      '\n'
26,0-26,1:      NL      '\n'
27,0-27,0:      DEDENT  ''
27,0-29,3:      STRING  '"""\n## Another Cell 1\n"""'
29,3-29,4:      NEWLINE '\n'
30,0-30,1:      NL      '\n'
31,0-31,1:      NL      '\n'
32,0-32,3:      NAME    'def'
32,4-32,8:      NAME    'main'
32,8-32,9:      OP      '('
32,9-32,10:     OP      ')'
32,10-32,11:    OP      ':'
32,11-32,12:    NEWLINE '\n'
33,0-33,4:      INDENT  '    '
33,4-33,9:      NAME    'hello'
33,9-33,10:     OP      '('
33,10-33,11:    OP      ')'
33,11-33,12:    NEWLINE '\n'
34,0-34,1:      NL      '\n'
35,0-35,1:      NL      '\n'
36,0-36,0:      DEDENT  ''
36,0-38,3:      STRING  '"""\n### Run this\n"""'
38,3-38,4:      NEWLINE '\n'
39,0-39,1:      NL      '\n'
40,0-40,2:      NAME    'if'
40,3-40,11:     NAME    '__name__'
40,12-40,14:    OP      '=='
40,15-40,25:    STRING  "'__main__'"
40,25-40,26:    OP      ':'
40,26-40,27:    NEWLINE '\n'
41,0-41,4:      INDENT  '    '
41,4-41,7:      NAME    'def'
41,8-41,12:     NAME    'what'
41,12-41,13:    OP      '('
41,13-41,14:    OP      ')'
41,14-41,15:    OP      ':'
41,15-41,16:    NEWLINE '\n'
42,0-42,8:      INDENT  '        '
42,8-42,12:     NAME    'main'
42,12-42,13:    OP      '('
42,13-42,14:    OP      ')'
42,14-42,15:    NEWLINE '\n'
43,4-43,4:      DEDENT  ''
43,4-43,9:      NAME    'print'
43,9-43,10:     OP      '('
43,10-43,14:    NAME    'what'
43,14-43,15:    OP      '('
43,15-43,16:    OP      ')'
43,16-43,17:    OP      ')'
43,17-43,18:    NEWLINE '\n'
44,0-44,1:      NL      '\n'
45,0-45,1:      NL      '\n'
46,0-46,0:      DEDENT  ''
46,0-48,3:      STRING  '"""\n## Another Cell 2\n"""'
48,3-48,4:      NEWLINE '\n'
49,0-49,0:      ENDMARKER       ''
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/Evgeny/somepath/lib/python2.7/site-packages/py2nb/__main__.py", line 21, in <module>
    main()
  File "/home/Evgeny/somepath/lib/python2.7/site-packages/py2nb/__main__.py", line 18, in main
    output_filename=args.destination)
  File "/home/Evgeny/somepath/lib/python2.7/site-packages/py2nb/tools.py", line 15, in python_to_notebook
    cvt = read(input_filename)
  File "/home/Evgeny/somepath/lib/python2.7/site-packages/py2nb/reader.py", line 16, in read
    out = list(nl_gen)
  File "/home/Evgeny/somepath/lib/python2.7/site-packages/py2nb/reader.py", line 56, in fix_newlines
    for token in tokens:
  File "/home/Evgeny/somepath/lib/python2.7/site-packages/py2nb/reader.py", line 27, in convert_toplevel_docstring
    for token in tokens:
TypeError: 'NoneType' object is not iterable
```

**Comment by blokhin** [comment]
This is virtualenv in Cygwin with:
```
$ python -V
Python 2.7.13
$ ipython -V
5.3.0
$ jupyter --version
4.3.0
```

**Comment by sklam** [comment]
I can confirm the bug to be on py2.7.  It works fine on py3.5.

**Comment by blokhin** [comment]
Ah sorry I haven't noticed there is no support of Python 2. My bad.
